import React from 'react';
import { Edit, TextInput, SimpleForm, required, PasswordInput } from 'react-admin';

const ProfileEdit = ({ staticContext, ...props }) => {
    return (
        <Edit
        /*
                As this component isn't loaded from a route generated by a <Resource>,
                I have to provide the id myself.
                As there is only one config for the current user, I decided to
                hard-code it here
            */
        id={localStorage.getItem("id")}
        /*
                For the same reason, I need to provide the resource and basePath props
                which are required by the Edit component
            */
           resource="profile"
           basePath="/my-profile"
           title="My Profile"
            redirect={false} // I don't need any redirection here, there's no list page
            {...props}
        >
            <SimpleForm>
                <TextInput source="name" validate={required()} />
                <TextInput source="email" validate={required()} />
                <PasswordInput source="password" validate={required()} />
            </SimpleForm>
        </Edit>
    );
};

export default ProfileEdit;